#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
numlockx &
usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom &
flameshot &
polybar main &
# 2 monitor
#polybar secondary &
dunst -conf ~/.config/dunst/dunstrc &
# xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144 &
# xrandr --output DisplayPort-1 --mode 1920x1080 --rate 144 &

bspc monitor -d 1 2 3 4 5 6
# 2 monitor
# bspc monitor DisplayPort-1 -d 1A 2A 3A 4A 5A 6A

bspc config border_width         0
bspc config window_gap           8
bspc config split_ratio          0.5
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#d4be98"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
